// Six races (Lineage 2 inspired). Each entry has visuals + stat modifiers.
// Stats are flat additions to base, applied at character creation.
export const RACES = [
  {
    id: "human",
    icon: "🛡",
    name: "Человек",
    desc: "Сбалансированная раса. Воин или маг.",
    skin: 0xe6c0a3,
    hair: 0x6f4e2a,
    height: 1.0,
    cape: 0x355978,
    classes: ["fighter", "mystic"],
    stats: { str: 40, dex: 30, con: 43, int: 21, wit: 11, men: 25 },
  },
  {
    id: "elf",
    icon: "🏹",
    name: "Эльф",
    desc: "Ловкие и магически одарённые. Лес и луна.",
    skin: 0xf3d4b8,
    hair: 0xc9a14a,
    height: 1.05,
    cape: 0x3e7a4a,
    earsLong: true,
    classes: ["fighter", "mystic"],
    stats: { str: 36, dex: 35, con: 36, int: 23, wit: 14, men: 26 },
  },
  {
    id: "darkelf",
    icon: "🗡",
    name: "Тёмный эльф",
    desc: "Изгнанники. Серая кожа, ассасины и колдуны.",
    skin: 0x9a8aa8,
    hair: 0x12131a,
    height: 1.04,
    cape: 0x361532,
    earsLong: true,
    classes: ["fighter", "mystic"],
    stats: { str: 41, dex: 34, con: 32, int: 25, wit: 12, men: 26 },
  },
  {
    id: "orc",
    icon: "🪓",
    name: "Орк",
    desc: "Сильнейшие воины. Шаманы и берсеркеры.",
    skin: 0x6a8a4f,
    hair: 0x2e1a0a,
    height: 1.15,
    cape: 0x6e2f15,
    tusks: true,
    classes: ["raider", "shaman"],
    stats: { str: 45, dex: 25, con: 47, int: 18, wit: 12, men: 27 },
  },
  {
    id: "dwarf",
    icon: "⛏",
    name: "Гном",
    desc: "Мастера ковки и торговли. Крепкие как камень.",
    skin: 0xe6b08a,
    hair: 0x8a3a1a,
    height: 0.78,
    cape: 0x7a5a2a,
    beard: true,
    classes: ["scavenger", "artisan"],
    stats: { str: 39, dex: 29, con: 45, int: 20, wit: 10, men: 27 },
  },
  {
    id: "kamael",
    icon: "🦋",
    name: "Камаэль",
    desc: "Тёмные крылатые воители. Истинные хранители Шилен.",
    skin: 0xd0c0b8,
    hair: 0xefefef,
    height: 1.02,
    cape: 0x1a1620,
    wings: true,
    classes: ["soldier", "trooper"],
    stats: { str: 42, dex: 32, con: 38, int: 22, wit: 12, men: 24 },
  },
];

export const CLASSES = {
  fighter: { id: "fighter", name: "Воин", desc: "Меч и щит. Высокий HP, ближний бой.", baseHp: 80, baseMp: 20, atk: 12, mAtk: 4 },
  mystic:  { id: "mystic",  name: "Маг",  desc: "Посох, заклинания. Высокий MP.",       baseHp: 60, baseMp: 60, atk: 6,  mAtk: 14 },
  raider:  { id: "raider",  name: "Налётчик", desc: "Орк-воин. Двуручное оружие.",       baseHp: 100, baseMp: 15, atk: 16, mAtk: 2 },
  shaman:  { id: "shaman",  name: "Шаман", desc: "Поддержка и стихии.",                  baseHp: 70, baseMp: 50, atk: 8,  mAtk: 12 },
  scavenger: { id: "scavenger", name: "Старатель", desc: "Гном-добытчик. Лут х1.5.",     baseHp: 75, baseMp: 25, atk: 10, mAtk: 5 },
  artisan: { id: "artisan", name: "Ремесленник", desc: "Гном-крафтер. Создаёт предметы.", baseHp: 70, baseMp: 35, atk: 9, mAtk: 7 },
  soldier: { id: "soldier", name: "Солдат", desc: "Камаэль-боец, лук-арбалет.",          baseHp: 75, baseMp: 30, atk: 13, mAtk: 6 },
  trooper: { id: "trooper", name: "Гвардеец", desc: "Камаэль-воин с двуручом.",          baseHp: 85, baseMp: 25, atk: 14, mAtk: 5 },
};

export function getRace(id) { return RACES.find((r) => r.id === id) || RACES[0]; }
export function getClass(id) { return CLASSES[id] || CLASSES.fighter; }
